name: stinfo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  buttons_tabbar: ^1.3.7+1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: NanumSquare
      fonts:
        - asset: assets/fonts/NanumSquareL.ttf
          weight: 200
        - asset: assets/fonts/NanumSquareL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareR.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareR.ttf
          weight: 500
        - asset: assets/fonts/NanumSquareR.ttf
          weight: 600
        - asset: assets/fonts/NanumSquareB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareEB.ttf
          weight: 900
    - family: BMJUA
      fonts:
        - asset: assets/fonts/BMJUA.ttf
          weight: 400
        - asset: assets/fonts/BMJUA.ttf
          weight: 700
